name: psplash
base: core20
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: psplash boot splash
description: |
  Boot splash screen taken from yocto project

grade: stable
confinement: strict

parts:
  psplash:
    # See 'snapcraft plugins'
    plugin: autotools
    source: .
    autotools-configure-parameters:
      - --build=${SNAPCRAFT_ARCH_TRIPLET}
      - --host=${SNAPCRAFT_ARCH_TRIPLET}
      - --prefix=/usr
      - --with-systemd
      - --with-font=ubuntu
      - --
      - CC=${SNAPCRAFT_ARCH_TRIPLET}-gcc
      - LIBS="-lsystemd"
    override-pull: |
      snapcraftctl pull
      sed -i 's/POKY_IMG/CORE_IMG/g' psplash.c
      otf2bdf -p 22 -r 75 -v \
              $(ls /usr/share/fonts/truetype/*/Ubuntu-R.ttf) \
              -o ubuntu.bdf || res=$?
      if [ "$res" != "8" ]; then
        echo "Unexpected exit code from otf2bdf, should be 8"
        exit 1
      fi
      bdftobogl ubuntu.bdf > ubuntu-font.h
      sed -i \
          -e 's/#include "bogl\.h"/#include "psplash\.h"/g' \
          -e 's/struct bogl_font font_ubuntu/PSplashFont ubuntu_font/g' \
          ubuntu-font.h
      ln -sf core_orange_hex.png psplash-core.png
      ./make-image-header.sh psplash-core.png CORE
      sed -i \
          's/psplash-poky-img.h/psplash-core-img.h/g' \
          Makefile.am psplash.c
    override-build: |
      snapcraftctl build
      install -m 644 -T -D \
        psplash-start.service \
        ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system/psplash-start.service
      install -m 644 -T -D \
        psplash-systemd.service \
        ${SNAPCRAFT_PART_INSTALL}/usr/lib/systemd/system/psplash-systemd.service

build-packages:
  - fonts-ubuntu
  - libbogl-dev
  - libgdk-pixbuf2.0-bin
  - libsystemd-dev
  - pkg-config
  - otf2bdf
